spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    dirver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /console
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    org.hibernate.SQL: debug